'use strict';

const service = require('../../src/services/drugInteractionService');
const dataset = require('../../src/data/drugInteractions.json');

const med = (name, id = null) => ({ id, name });

describe('drug interaction dataset', () => {
  it('is clearly marked as demo data', () => {
    expect(dataset.isDemoData).toBe(true);
    expect(dataset.demoDataNotice).toMatch(/DEMO DATA/i);
    expect(dataset.demoDataNotice).toMatch(/NOT.*complete|not a complete/i);
    expect(dataset.sourceNotes).toMatch(/no interaction in this file was generated by a language model/i);
  });

  it('has unique ids and complete records', () => {
    const ids = new Set();
    for (const entry of dataset.interactions) {
      expect(ids.has(entry.id)).toBe(false);
      ids.add(entry.id);
      expect(entry.drugA).toBeTruthy();
      expect(entry.drugB).toBeTruthy();
      expect(['major', 'moderate', 'minor']).toContain(entry.severity);
      expect(entry.description.length).toBeGreaterThan(20);
      expect(Array.isArray(entry.precautions)).toBe(true);
      expect(entry.precautions.length).toBeGreaterThan(0);
    }
  });

  it('never pairs a drug with itself', () => {
    for (const entry of dataset.interactions) {
      expect(entry.drugA).not.toBe(entry.drugB);
    }
  });
});

describe('checkInteractions — matching', () => {
  it('finds a documented major interaction', () => {
    const result = service.checkInteractions([med('Warfarin'), med('Aspirin')]);
    expect(result.summary.total).toBe(1);
    expect(result.findings[0].severity).toBe('major');
    expect(result.findings[0].description).toMatch(/bleeding/i);
    expect(result.findings[0].precautions.length).toBeGreaterThan(0);
  });

  it('matches through brand names', () => {
    const result = service.checkInteractions([med('Coumadin'), med('Tab. Ecosprin 75mg')]);
    expect(result.summary.total).toBe(1);
    expect(result.findings[0].medicineA.substance).toBe('warfarin');
    expect(result.findings[0].medicineB.substance).toBe('aspirin');
  });

  it('matches regardless of the order the medicines are supplied in', () => {
    const forward = service.checkInteractions([med('Warfarin'), med('Ibuprofen')]);
    const reverse = service.checkInteractions([med('Ibuprofen'), med('Warfarin')]);
    expect(forward.summary.total).toBe(reverse.summary.total);
    expect(forward.findings[0].interactionId).toBe(reverse.findings[0].interactionId);
  });

  it('decomposes combination products and checks each substance', () => {
    const result = service.checkInteractions([
      med('Warfarin'),
      med('Ibuprofen + Paracetamol')
    ]);
    const ids = result.findings.map((f) => f.interactionId).sort();
    expect(ids).toEqual(['DDI-002', 'DDI-030']);
  });

  it('checks every pair in a longer medicine list', () => {
    const result = service.checkInteractions([
      med('Warfarin'),
      med('Aspirin'),
      med('Ibuprofen'),
      med('Metformin')
    ]);
    const ids = result.findings.map((f) => f.interactionId);
    expect(ids).toEqual(expect.arrayContaining(['DDI-001', 'DDI-002', 'DDI-005']));
    expect(result.summary.medicinesChecked).toBe(4);
  });

  it('sorts findings with the most severe first', () => {
    const result = service.checkInteractions([
      med('Levothyroxine'),
      med('Omeprazole'),
      med('Warfarin'),
      med('Aspirin')
    ]);
    const ranks = { major: 3, moderate: 2, minor: 1 };
    const values = result.findings.map((f) => ranks[f.severity]);
    expect([...values].sort((a, b) => b - a)).toEqual(values);
    expect(result.summary.highestSeverity).toBe('major');
  });

  it('carries the medicine ids through so the UI can link back', () => {
    const result = service.checkInteractions([
      med('Warfarin', 'id-a'),
      med('Aspirin', 'id-b')
    ]);
    expect(result.findings[0].medicineA.id).toBe('id-a');
    expect(result.findings[0].medicineB.id).toBe('id-b');
  });
});

describe('checkInteractions — no false positives', () => {
  it('reports nothing for a pair absent from the dataset', () => {
    const result = service.checkInteractions([med('Vitamin C'), med('Zinc')]);
    expect(result.summary.total).toBe(0);
    expect(result.findings).toEqual([]);
  });

  it('never pairs a medicine with itself', () => {
    expect(service.checkInteractions([med('Aspirin')]).summary.total).toBe(0);
    expect(service.checkInteractions([med('Aspirin'), med('Ecosprin')]).summary.total).toBe(0);
  });

  it('handles an empty or unusable list', () => {
    expect(service.checkInteractions([]).summary.total).toBe(0);
    expect(service.checkInteractions([med('')]).summary.medicinesChecked).toBe(0);
    expect(service.checkInteractions([med('500 mg tablet')]).summary.medicinesChecked).toBe(0);
  });

  it('does not duplicate a finding for the same medicine pair', () => {
    const result = service.checkInteractions([
      med('Warfarin + Aspirin'),
      med('Aspirin')
    ]);
    const keys = result.findings.map(
      (f) => `${f.medicineA.name}|${f.medicineB.name}|${f.interactionId}`
    );
    expect(new Set(keys).size).toBe(keys.length);
  });
});

describe('checkInteractions — determinism', () => {
  it('returns identical output for identical input', () => {
    const input = [med('Warfarin'), med('Aspirin'), med('Ibuprofen')];
    expect(JSON.stringify(service.checkInteractions(input))).toBe(
      JSON.stringify(service.checkInteractions(input))
    );
  });

  it('marks its method as a dataset lookup, never a generated answer', () => {
    const result = service.checkInteractions([med('Warfarin'), med('Aspirin')]);
    expect(result.method).toBe('deterministic-dataset-lookup');
    expect(result.findings.every((f) => f.source === 'dataset')).toBe(true);
  });

  it('returns every fact verbatim from the dataset', () => {
    const result = service.checkInteractions([med('Warfarin'), med('Aspirin')]);
    const source = dataset.interactions.find((i) => i.id === result.findings[0].interactionId);
    expect(result.findings[0].description).toBe(source.description);
    expect(result.findings[0].mechanism).toBe(source.mechanism);
    expect(result.findings[0].precautions).toEqual(source.precautions);
    expect(result.findings[0].severity).toBe(source.severity);
  });

  it('always attaches the demo-data notice and a disclaimer', () => {
    const result = service.checkInteractions([med('Paracetamol')]);
    expect(result.dataset.isDemoData).toBe(true);
    expect(result.dataset.demoDataNotice).toMatch(/DEMO DATA/i);
    expect(result.disclaimer).toMatch(/not a substitute for professional advice/i);
    expect(result.disclaimer).toMatch(/only means this dataset holds no record/i);
  });
});

describe('duplicate therapy detection', () => {
  it('flags two NSAIDs taken together', () => {
    const result = service.checkInteractions([med('Ibuprofen'), med('Naproxen')]);
    const group = result.duplicateTherapy.find((g) => g.groupId === 'DUP-NSAID');
    expect(group).toBeTruthy();
    expect(group.medicines).toHaveLength(2);
    expect(group.severity).toBe('moderate');
  });

  it('flags two statins as a major duplication', () => {
    const result = service.checkInteractions([med('Atorvastatin'), med('Simvastatin')]);
    const group = result.duplicateTherapy.find((g) => g.groupId === 'DUP-STATIN');
    expect(group.severity).toBe('major');
  });

  it('flags hidden paracetamol in two products', () => {
    const result = service.checkInteractions([med('Dolo 650'), med('Crocin Advance')]);
    const group = result.duplicateTherapy.find((g) => g.groupId === 'DUP-PARACETAMOL');
    expect(group).toBeTruthy();
    expect(group.precautions.join(' ')).toMatch(/4 g/);
  });

  it('does not flag a single member of a group', () => {
    const result = service.checkInteractions([med('Ibuprofen'), med('Metformin')]);
    expect(result.duplicateTherapy).toEqual([]);
  });
});

describe('lookupPair', () => {
  it('finds a known pair either way round', () => {
    expect(service.lookupPair('warfarin', 'aspirin').id).toBe('DDI-001');
    expect(service.lookupPair('aspirin', 'warfarin').id).toBe('DDI-001');
  });

  it('returns null for an unknown or degenerate pair', () => {
    expect(service.lookupPair('aspirin', 'aspirin')).toBeNull();
    expect(service.lookupPair('aspirin', 'unobtanium')).toBeNull();
    expect(service.lookupPair('', 'aspirin')).toBeNull();
    expect(service.lookupPair(null, 'aspirin')).toBeNull();
  });
});

describe('datasetInfo', () => {
  it('reports provenance and states that no LLM is involved', () => {
    const info = service.datasetInfo();
    expect(info.isDemoData).toBe(true);
    expect(info.llmInvolved).toBe(false);
    expect(info.method).toBe('deterministic-dataset-lookup');
    expect(info.interactionCount).toBe(dataset.interactions.length);
    expect(info.knownSubstanceCount).toBeGreaterThan(30);
  });
});
