'use strict';

const fs = require('fs/promises');
const path = require('path');
const sharp = require('sharp');

const { config } = require('../config/env');
const logger = require('../config/logger');

/**
 * Stored filenames are generated by the upload middleware, so they always match
 * this shape. Anything else is rejected before it can reach the file system.
 */
const SAFE_FILENAME = /^[A-Za-z0-9._-]+$/;

/** Resolves a stored filename to an absolute path, refusing traversal. */
function resolveStoredPath(subdir, filename) {
  if (typeof filename !== 'string' || !SAFE_FILENAME.test(filename) || filename.includes('..')) {
    throw new Error('Invalid file path');
  }
  const base = path.resolve(config.uploads.dir, subdir);
  const resolved = path.resolve(base, filename);
  if (!resolved.startsWith(base + path.sep)) {
    throw new Error('Invalid file path');
  }
  return resolved;
}

/**
 * Normalises an uploaded medicine photo: strips EXIF metadata (which can carry
 * GPS coordinates), caps the dimensions and writes a square thumbnail used by
 * the visual reminder card.
 *
 * @returns {Promise<{filename: string, thumbnailFilename: string, size: number}>}
 */
async function processMedicineImage(file) {
  const source = resolveStoredPath('medicines', file.filename);
  const parsed = path.parse(file.filename);
  const normalisedName = `${parsed.name}.webp`;
  const thumbnailName = `${parsed.name}-thumb.webp`;

  const normalisedPath = resolveStoredPath('medicines', normalisedName);
  const thumbnailPath = resolveStoredPath('medicines', thumbnailName);

  await sharp(source)
    .rotate() // honour EXIF orientation before metadata is dropped
    .resize({ width: 1024, height: 1024, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(normalisedPath);

  await sharp(source)
    .rotate()
    .resize({ width: 320, height: 320, fit: 'cover' })
    .webp({ quality: 78 })
    .toFile(thumbnailPath);

  // The original upload is no longer needed once both derivatives exist.
  await fs.unlink(source).catch(() => undefined);

  const { size } = await fs.stat(normalisedPath);
  return { filename: normalisedName, thumbnailFilename: thumbnailName, size };
}

/** Deletes a stored file and its thumbnail, ignoring anything already gone. */
async function removeStoredFile(subdir, filename) {
  if (!filename) return;
  try {
    await fs.unlink(resolveStoredPath(subdir, filename)).catch(() => undefined);
    const parsed = path.parse(filename);
    await fs
      .unlink(resolveStoredPath(subdir, `${parsed.name}-thumb.webp`))
      .catch(() => undefined);
  } catch (err) {
    logger.warn(`Could not remove file ${subdir}/${filename}: ${err.message}`);
  }
}

async function fileExists(subdir, filename) {
  try {
    await fs.access(resolveStoredPath(subdir, filename));
    return true;
  } catch {
    return false;
  }
}

module.exports = { processMedicineImage, removeStoredFile, resolveStoredPath, fileExists };
