import { useState } from 'react';
import { Link } from 'react-router-dom';
import { assistantApi } from '../services/endpoints';
import useApi from '../hooks/useApi';
import { Card, Alert, Badge, Stat, Spinner, EmptyState, ErrorState } from '../components/ui';
import { percent, ADHERENCE_LABEL } from '../utils/format';

const SEVERITY_STYLE = {
  positive: { variant: 'success', icon: '✅' },
  neutral: { variant: 'info', icon: 'ℹ️' },
  attention: { variant: 'warning', icon: '⚠️' }
};

const CATEGORY_LABEL = {
  adherence: 'Adherence',
  trend: 'Trend',
  timing: 'Timing',
  behaviour: 'Patterns',
  refill: 'Refills'
};

export default function Insights() {
  const [windowDays, setWindowDays] = useState(30);
  const { data, loading, error, reload } = useApi(
    () => assistantApi.insights({ windowDays }),
    [windowDays]
  );

  return (
    <>
      <div className="page__header">
        <div>
          <h1 className="mb-0">Health insights</h1>
          <p className="page__subtitle">
            Observations drawn only from your own medication records.
          </p>
        </div>
        <select
          className="select"
          value={windowDays}
          onChange={(event) => setWindowDays(Number(event.target.value))}
          style={{ width: 'auto' }}
          aria-label="Time window"
        >
          <option value={7}>Last 7 days</option>
          <option value={30}>Last 30 days</option>
          <option value={90}>Last 90 days</option>
        </select>
      </div>

      <Alert variant="neutral" title="These describe your routine, not your health">
        <p className="mb-0">
          MedGuardian looks at when you took, skipped or missed doses and how your stock is moving.
          It never interprets a symptom, names a condition or suggests a treatment. Each observation
          below shows the exact rule that produced it.
        </p>
      </Alert>

      {loading && !data ? (
        <Spinner large label="Looking at your records…" />
      ) : error ? (
        <ErrorState error={error} onRetry={reload} />
      ) : !data ? null : (
        <>
          <div className="grid grid--4 mb-5">
            <Stat
              label="Adherence"
              value={percent(data.adherence.adherenceScore)}
              meta={ADHERENCE_LABEL[data.adherence.adherenceLabel]}
            />
            <Stat
              label="Trend"
              value={
                data.trend.direction === 'insufficient_data'
                  ? '—'
                  : data.trend.change > 0
                    ? `+${data.trend.change}`
                    : String(data.trend.change)
              }
              meta={
                data.trend.direction === 'insufficient_data'
                  ? 'Not enough history to compare'
                  : `${data.trend.direction} vs the previous ${data.windowDays} days`
              }
            />
            <Stat label="Doses taken" value={data.adherence.taken} meta={`${data.adherence.skipped} skipped`} />
            <Stat label="Doses missed" value={data.adherence.missed} meta="No record was made" />
          </div>

          {data.insights.length === 0 ? (
            <Card>
              <EmptyState icon="💡" title="No observations yet">
                Record a few doses and your patterns will start showing up here.
              </EmptyState>
            </Card>
          ) : (
            <div className="stack">
              {data.insights.map((insight) => {
                const style = SEVERITY_STYLE[insight.severity] || SEVERITY_STYLE.neutral;
                return (
                  <Card key={insight.id}>
                    <div className="row row--between mb-2">
                      <h3 className="mb-0">
                        <span aria-hidden="true">{style.icon}</span> {insight.title}
                      </h3>
                      <Badge variant={style.variant}>
                        {CATEGORY_LABEL[insight.category] || insight.category}
                      </Badge>
                    </div>
                    <p className="mb-2">{insight.detail}</p>
                    <div className="text-xs text-muted mono">Rule: {insight.rule}</div>
                  </Card>
                );
              })}
            </div>
          )}

          <div className="row mt-5">
            <Link to="/adherence" className="btn btn--secondary">
              See the full adherence breakdown
            </Link>
            <Link to="/history" className="btn btn--ghost">
              View dose history
            </Link>
          </div>

          <p className="text-xs text-muted mt-4">
            {data.disclaimer} · Method: {data.method} · diagnostic: {String(data.isDiagnostic)} ·
            generated by a model: {String(data.generatedByModel)}
          </p>
        </>
      )}
    </>
  );
}
